/**
 * All question variants supported by the game. For more information about individual variants, see
 * the variant questions generators in `$lib/server`.
 */
export type QuestionVariant =
	| 'duration'
	// The player guesses the whether the conversation is fake or real.
	| 'fake'
	| 'platform'
	| 'react'
	// The player guesses the response to the last message in the conversation.
	| 'respond'
	// The player guesses when the last message in the conversation was sent.
	| 'when'
	| 'who';

/**
 * Represents a message in a conversation to be used in a question This is slightly different from
 * the representation in the database to allow simplified rendering.
 */
export type QuestionMessage = {
	content: string;
	date: Date;
	isMedia: boolean;
	participant: string;
	reaction: string;
};

/**
 * Represents a question that is asked to the player. This is generated by the server and rendered
 * by the client. All question variants share the same format, but may be rendered differently.
 */
export type Question = {
	answer: string;
	choices: Array<string>;
	messages: Array<QuestionMessage>;
	variant: QuestionVariant;
};
